language: rust

branches:
  only:
    - staging
    - trying
    - master

matrix:

  allow_failures:
   - rust: nightly
  fast_finish: true

  include:
    - name: cargo test ios-simulator
      os: osx
      osx_image: xcode11.4
      rust: stable
      env: CI_STAGE_IOS_SIMULATOR_TEST=yes
      before_script:
       - rustup target add x86_64-apple-ios
       # download cargo-dinghy and set it up for running on an emulator.
       - curl -L https://github.com/snipsco/dinghy/releases/download/cargo-dinghy%2F0.4.37/cargo-dinghy-macos.tgz -o cargo-dinghy-macos.tar.gz
       - tar -zxvf cargo-dinghy-macos.tar.gz
       - mkdir -p $HOME/.cargo/bin
       - cp cargo-dinghy-macos/cargo-dinghy $HOME/.cargo/bin

script:
  - if [[ "$CI_STAGE_IOS_SIMULATOR_TEST" == "yes" ]]; then
      RUNTIME_ID=$(xcrun simctl list runtimes | grep iOS | cut -d ' ' -f 7 | tail -1);
      export SIM_ID=$(xcrun simctl create My-iphone11 com.apple.CoreSimulator.SimDeviceType.iPhone-11 $RUNTIME_ID);
      xcrun simctl boot $SIM_ID;
      cd gdnative-core;
      cargo dinghy --platform auto-ios-x86_64 test;
      cd ..;
      cd gdnative-sys;
      cargo dinghy --platform auto-ios-x86_64 test;
    fi

